# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "my-pins")
v <- vetiver_pin_read(b, "xgb_big_mac_classifier", version = "20250708T143824Z-2a9fb")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
